from _typeshed import Incomplete

RE_SOURCE_FILENAME: Incomplete
RE_TARGET_FILENAME: Incomplete
RE_DIFF_GIT_HEADER: Incomplete
RE_DIFF_GIT_HEADER_URI_LIKE: Incomplete
RE_DIFF_GIT_HEADER_NO_PREFIX: Incomplete
RE_DIFF_GIT_DELETED_FILE: Incomplete
RE_DIFF_GIT_NEW_FILE: Incomplete
RE_HUNK_HEADER: Incomplete
RE_HUNK_BODY_LINE: Incomplete
RE_HUNK_EMPTY_BODY_LINE: Incomplete
RE_NO_NEWLINE_MARKER: Incomplete
RE_BINARY_DIFF: Incomplete
DEFAULT_ENCODING: str
DEV_NULL: str
LINE_TYPE_ADDED: str
LINE_TYPE_REMOVED: str
LINE_TYPE_CONTEXT: str
LINE_TYPE_EMPTY: str
LINE_TYPE_NO_NEWLINE: str
LINE_VALUE_NO_NEWLINE: str
